# CMake generated Testfile for 
# Source directory: F:/Document/Graphics/code/pbrt-v3/src/ext/glog
# Build directory: F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(demangle "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/Debug/demangle_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(demangle "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/Release/demangle_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(demangle "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/MinSizeRel/demangle_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(demangle "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/RelWithDebInfo/demangle_unittest.exe")
else()
  add_test(demangle NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/Debug/logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/Release/logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/MinSizeRel/logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/RelWithDebInfo/logging_unittest.exe")
else()
  add_test(logging NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stl_logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/Debug/stl_logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stl_logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/Release/stl_logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stl_logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/MinSizeRel/stl_logging_unittest.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stl_logging "F:/Document/Graphics/code/pbrt-v3/build/src/ext/glog/RelWithDebInfo/stl_logging_unittest.exe")
else()
  add_test(stl_logging NOT_AVAILABLE)
endif()
